src/web/config/urls.py
from django.contrib import admin
from django.urls import path, include


# for clothes static path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("hipdrobe.urls")),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),


]


urlpatterns += static(settings.CLOTHES_URL, document_root=settings.CLOTHES_ROOT)
urlpatterns += static(settings.CLOTHES_URL_TMP, document_root=settings.CLOTHES_ROOT_TMP)

src/web/hipdrobe/urls.py
from django.urls import path
from . import views, apis
# from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views


app_name = "hipdrobe"
urlpatterns = [
    path('', views.index, name='index'),
    path('wardrobe/items/', views.items, name="items" ),
    path('wardrobe/coordi/', views.coordi, name="coordi"),
    path('wardrobe/coordi/<int:c_id>/detail/', views.coordi_detail, name="coordi_detail"),
    path('wardrobe/coordi/<int:c_id>/update/', views.coordi_update, name="coordi_update"),
    path('wardrobe/stat/', views.stat, name="stat" ),
    
    path('signup/',views.signup, name="signup"),
    path('login/' ,views.signin, name="signin"),
    path('logout/' ,views.logout, name="logout"),

    # auth_views 이용
    # path('signup/', views.UserCreateView.as_view(), name='signup'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    




    # 페이지 요청이 아닌 기능 요청은 아래쪽에서 관리
    # 대표적으로 AJAX 요청이 여기에 해당
    path('apis/parts/', apis.parts, name="parts"),
    path('apis/cate1/', apis.cate1, name="cate1"),
    path('apis/cate2/', apis.cate2, name="cate2"),
    path('apis/upload/', apis.upload, name="upload"),
    path('apis/clothes/', apis.clothes, name="clothes"),
    path('apis/additem/', apis.additem, name="additem"),
    path('apis/coordi/', apis.coordi, name="coordi_list"),
    path('apis/coordi/new/', apis.coordi_new, name="coordi_new"),
    path('apis/coordi/delete/', apis.coordi_delete, name="coordi_delete"),
    path('apis/coordi/edit/', apis.coordi_edit, name="coordi_edit"),
    path('apis/daily-status/', apis.daily_status, name="daily_status"),
    # path('check_id/',views.check_id,name="check_id"),
    path('apis/clothes_detail/', apis.clothes_detail, name="clothes_detail"),
    path('apis/updateitem/', apis.updateitem, name="updateitem"),
    path('apis/delete_clothes/', apis.delete_clothes, name="delete_clothes"),
]

src/web/hipdrobe/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model






# Create your models here.


class User(AbstractUser):
    
    gender = models.BooleanField(null=True)
    level_point=models.IntegerField(default=0)
    level=models.IntegerField(default=1)
    count_top=models.IntegerField(default=0) # 상의 보유 개수
    count_bottom=models.IntegerField(default=0) # 하의 보유 개수
    count_shoes=models.IntegerField(default=0) # 신발 보유 개수

    def __str__(self):
        return f'{self.id} | {self.username}'


class Part(models.Model):
    part = models.CharField(primary_key=True, max_length=10)
    part_name = models.CharField(max_length=10)

    def __str__(self):
        return self.part_name


class Cate1(models.Model):
    cate1 = models.CharField(primary_key=True, max_length=20)
    cate1_name = models.CharField(max_length=20)
    part = models.ForeignKey(Part, on_delete=models.CASCADE)

    def __str__(self):
        return self.cate1_name


class Cate2(models.Model):
    cate2 = models.CharField(max_length=20)
    cate2_name = models.CharField(max_length=20)
    cate1 = models.ForeignKey(Cate1, on_delete=models.CASCADE)
    worn = models.IntegerField(default=0) # 해당 카테고리 옷 입은 횟수

    def __str__(self):
        return self.cate2_name

    
class Clothes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # 유저id
    cate1_name = models.CharField(max_length=20) # 카테고리1 이름
    cate2_name = models.CharField(max_length=20) # 카테고리2 이름
    part = models.CharField(max_length=10) # 부위
    url = models.CharField(max_length=256) # 옷 사진 url
    color = models.CharField(max_length=40, null=True) # 색상
    solid = models.BooleanField(null=True) # 단색 여부
    pattern = models.CharField(max_length=15, null=True) # solid, stripe, dot, printing
    season = models.CharField(max_length=30, null=True) # multi-select로 (봄, 여름, 가을, 겨울)
    descript = models.CharField(max_length=100, null=True) # 비고
    worn = models.IntegerField(default=0) # 옷 입은 횟수
    brand = models.CharField(max_length=30, null=True)
    texture = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f"{self.part} | {self.cate1_name} | {self.cate2_name}"


class Coordi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    elem_list = models.TextField()
    is_daily = models.BooleanField()
    bg_type = models.CharField(max_length=20)
    wear_at = models.CharField(max_length=10, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id} | {'데일리룩' if self.is_daily else '일반코디'} | {self.user.id} | {self.title}"

src/web/hipdrobe/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth import get_user_model
from django.core import validators
from django import forms
from django.contrib.auth.password_validation import validate_password
class UserForm(forms.ModelForm):
    gender = forms.TypedChoiceField(
                coerce=lambda x: x == 'True',
                choices=((False, 'Male'), (True, 'Female')),
                widget=forms.RadioSelect,
                required=False
                
            )
    
    class Meta: 
        model = get_user_model()

        fields = ['username', 'email', 'password','gender']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password' : forms.PasswordInput(attrs={'class': 'form-control'}),
            

        }
        labels = {
            'username': 'ID',
            'email': 'email',
            'password': 'password',
            'gender':'gender',
        }

class LoginForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'password']
# 글자수 제한
def __init__(self, *args, **kwargs):
    super(UserForm, self).__init__( *args, **kwargs)
    self.fields['email'].widget.attrs['maxlength'] =59
    

src/web/hipdrobe/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, get_user_model
import simplejson as json
from .forms import UserForm, LoginForm

# Model
from .models import *

# Custom
from .utils import _coordi_to_dict








# Create your views here.
# -----------------------------------------------------------------------------
# index
# -----------------------------------------------------------------------------
def index(request):
    return render(request, 'hipdrobe/index.html')


# -----------------------------------------------------------------------------
# wardrobe menu
# -----------------------------------------------------------------------------
def items(request):
    # 로그인 안 해도 화면은 보여주고 실제 동작 할때 로그인 하라고 하는 게 나을 것
    # 같아서 로그인 체크 안 함

    # 시연용 테스트 코드 
    # 실제로 구현할 땐 이렇게 하면 안 되지만 그냥 보여주기 용
    # 실제로 구현할 땐 서버에서 일정 주기로 전체 정보를 갱신하여 갖고있도록 해 놓고
    # 각 유저 것만 조회하여 계산...

    if request.user.is_active:
        try:
            list_top = [ len(user.clothes_set.filter(part='상의'))
                for user in User.objects.all() ]
            my_top = len(request.user.clothes_set.filter(part='상의'))

            list_bottom = [ len(user.clothes_set.filter(part='하의'))
                for user in User.objects.all() ]
            my_bottom = len(request.user.clothes_set.filter(part='하의'))

            list_head = [ len(user.clothes_set.filter(part='머리'))
                for user in User.objects.all() ]
            my_head = len(request.user.clothes_set.filter(part='머리'))

            list_foot = [ len(user.clothes_set.filter(part='발'))
                for user in User.objects.all() ]
            my_foot = len(request.user.clothes_set.filter(part='발'))
            
            avg_top = sum(list_top) / len(list_top)
            max_top = max(max(list_top), 0.000001)
            avg_top = (avg_top / max_top) * 100
            my_top = (my_top / max_top) * 100

            avg_bottom = sum(list_bottom) / len(list_bottom)
            max_bottom = max(max(list_bottom), 0.000001)
            avg_bottom= (avg_bottom / max_bottom) * 100
            my_bottom = (my_bottom / max_bottom) * 100

            avg_head = sum(list_head) / len(list_head)
            max_head = max(max(list_head), 0.000001)
            avg_head = (avg_head / max_head) * 100
            my_head = (my_head / max_head) * 100

            avg_foot = sum(list_foot) / len(list_foot)
            max_foot = max(max(list_foot), 0.000001)
            avg_foot = (avg_foot / max_foot) * 100
            my_foot = (my_foot / max_foot) * 100
        except Exception as e:
            print(e)
            context = {}

        else:
            context = {
                'top': {
                    'avg': avg_top,
                    'my' : my_top
                },
                'bottom': {
                    'avg': avg_bottom,
                    'my' : my_bottom
                },
                'head': {
                    'avg': avg_head,
                    'my' : my_head
                },
                'foot': {
                    'avg': avg_foot,
                    'my' : my_foot
                }
            }
    else:
        context = {}
    
    # 시연용 테스트 코드 끝
    # -------------------------------------------------------------------------

    return render(request, 'hipdrobe/wardrobe-items.html', context)


def coordi(request):
    # 로그인 안 해도 화면은 보여주고 실제 동작 할때 로그인 하라고 하는 게 나을 것
    # 같아서 로그인 체크 안 함
    return render(request, 'hipdrobe/wardrobe-coordi.html')


@login_required
def coordi_detail(request, c_id):
    coordi = get_object_or_404(request.user.coordi_set, id=c_id)

    if coordi:
        coordi_dict = _coordi_to_dict(coordi)
        context = {
            'result': True,
            'data': coordi_dict
        }
    else:
        context = {
            'result': False,
            'reason': 'forbidden'
        }

    return render(request, 'hipdrobe/wardrobe-coordi-detail.html', context)


@login_required
def coordi_update(request, c_id):
    coordi = get_object_or_404(request.user.coordi_set, id=c_id)

    if coordi:
        coordi_dict = _coordi_to_dict(coordi)
        context = {
            'result': True,
            'data': coordi_dict
        }
    else:
        context = {
            'result': False,
            'reason': 'forbidden'
        }

    return render(request, 'hipdrobe/wardrobe-coordi-update.html', context)


def stat(request):
    # 여기에 로그인 세션 체크 등 코드가 들어가야 함
    return render(request, 'hipdrobe/wardrobe-stat.html')


def signup(request):
    if request.method == "POST":
        print("11")
        form = UserForm(request.POST)
        print("12")
        User = get_user_model()
        if form.is_valid():
            print("13")
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
            print(new_user)
            return redirect('hipdrobe:index')
        else:
            return render(request,'hipdrobe/login_Fail.html')
    else:
        print("33")
        form = UserForm()
        return render(request, 'hipdrobe/signup.html', {'form': form})

def signin(request):
    if request.method == "POST":
        
        form = LoginForm(request.POST)
        email = request.POST['email']
        print(email)
        password = request.POST['password']
        print(password)
        user = authenticate(username = email, password = password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('hipdrobe:index')
        else:
            return render(request,'hipdrobe/login_Fail.html')
    else:
        form = LoginForm()
        return render(request, 'hipdrobe/login.html', {'form': form})


@login_required
def logout(request):
    auth.logout(request)
    return redirect('hipdrobe:index')

src/web/hipdrobe/templates/hipdrobe/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}힙드로브 홈{% endblock %}
{% block local_head_resources %}
  <link rel="stylesheet" href="{% static 'hipdrobe/css/index.css' %}">
{% endblock %}
{% block bg %}
  {% include 'hipdrobe/include/_bd-carousel.html' %}
{% endblock %}
{% block content %}
  <div class="container-fluid content-wrap">
    <div class="content-main">
 
    </div>
  </div>
  
{% endblock %}
{% block content-bottom %}
  <div class="container-fluid content-bottom">
    <div class="content-bottom-elem">
      <p class="p-head">
        나만의 옷장에 아이템을 등록하고<br>
        부위별로 설정해 보세요!
      </p>
      <p class="p-body">
          머리 속으로 상상하는 것 보다<br>
          훨씬 좋은 조합을 찾을 수 있을걸요?<br>
          <i>Fashion Insight!</i>
      </p>
      <a href="{% url 'hipdrobe:items' %}"><ins><i>Go!</i></ins></a>
    </div>
    <hr>
    <div class="content-bottom-elem">
      <p class="p-head">
        힙드로브가 제공하는 나만의 힙스탯!<br>
        여러가지 재미있는 정보를 즐겨보세요!
      </p>
      <p class="p-body">
          나의 레벨은? 나는 옷이 많은 편? 적은 편?<br>
          나는 어떤 스타일의 옷을 주로 입을까?<br>
          <i>정보가 쌓이면 유의미한 정보를 얻을 수 있어요!</i>
      </p>
      <a href="{% url 'hipdrobe:stat' %}"><ins><i>Go!</i></ins></a>
    </div>
    <hr>
    <div class="content-bottom-elem">
      <p class="p-head">
        내가 가진 힙템들로 코디 포스트를 작성하고<br>
        다른 사람들과 공유해보세요.
      </p>
      <p class="p-body">
          내가 작성한 코디 포스트를 공유하고<br>
          다른 사람의 코디 포스트를 참조해보세요.<br>
          <i>안목이 늘면, Yo! 나도 패션리더!</i>
      </p>
      <a href="{% url 'hipdrobe:coordi' %}"><ins><i>Go!</i></ins></a>
    </div>
  </div>
{% endblock %}
{% block local_body_resources %}
  <script src="{% static 'hipdrobe/js/index.js' %}"></script>
{% endblock %}

src/web/hipdrobe/templates/hipdrobe/login.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>hipdrobe 로그인</title>
  <link rel="stylesheet" href="{% static 'hipdrobe/css/login.css' %}" />
  <link rel="shortcut icon" href="{% static 'hipdrobe/favicon/favicon.ico' %}" type="image/x-icon">
</head>

<body>

<div class="page">
    
  <div class="container">
      
    <div class="left">
      <!-- <div id="container2"> -->
        <div id="wrapper">    
          <br>    
          <h1>Hipdrobe</h1>
        </div>
      <!-- </div> -->
      &ensp;&ensp;<div class="eula">옷장관리 & 소통으로 Hipster가 되어보세요!</div>
      
      <div class="back">
          <div class="button_base b10_tveffect">
              <div style="margin-top:45px; margin-left:30px">회원가입</div>
              <div style="margin-top:45px; margin-left:30px">
                  <div><a href="{% url 'hipdrobe:signup'%}">회원가입</a></div>
                  <div><a href="{% url 'hipdrobe:signup'%}">회원가입</a></div>
                  <div><a href="{% url 'hipdrobe:signup'%}">회원가입</a></div>
              </div>
          </div>
      </div>
      

      <div class="back">
          <div class="button_base b10_tveffect">
              <div style="margin-top:45px; margin-left:160px">메인페이지</div>
              <div style="margin-top:45px; margin-left:160px">
                  
                  <div><a href="{% url 'hipdrobe:index'%}" >메인 페이지</a></div>
                  <div><a href="{% url 'hipdrobe:index'%}" >메인 페이지</a></div>
                  <div><a href="{% url 'hipdrobe:index'%}" >메인 페이지</a></div>
                
              </div>
          </div>
      </div>
      
      
      <!-- <div class="mainpage">
          <a href="{% url 'hipdrobe:index'%}"  class="href">메인 페이지</a>
          &ensp;&ensp;
          <a href="{% url 'hipdrobe:signup'%}"  class="href" style="margin-right: 25px;">회원가입</a>  
      </div> -->
      <br>
      <br>
      <br>
      
      
      </div>
    
    <div class="right">
      <svg viewBox="0 0 320 300">
        <defs>
          <linearGradient
                          inkscape:collect="always"
                          id="linearGradient"
                          x1="13"
                          y1="193.49992"
                          x2="307"
                          y2="193.49992"
                          gradientUnits="userSpaceOnUse">
            <stop
                  style="stop-color:#ff00ff;"
                  offset="0"
                  id="stop876" />
            <stop
                  style="stop-color:#ff0000;"
                  offset="1"
                  id="stop878" />
          </linearGradient>
        </defs>
        <path d="m 40,120.00016 239.99984,-3.2e-4 c 0,0 24.99263,0.79932 25.00016,35.00016 0.008,34.20084 -25.00016,35 -25.00016,35 h -239.99984 c 0,-0.0205 -25,4.01348 -25,38.5 0,34.48652 25,38.5 25,38.5 h 215 c 0,0 20,-0.99604 20,-25 0,-24.00396 -20,-25 -20,-25 h -190 c 0,0 -20,1.71033 -20,25 0,24.00396 20,25 20,25 h 168.57143" />
      </svg>
      <div class="form">
        <form method="post" action="{% url 'hipdrobe:signin' %}" class="sign-in-form">
            {%csrf_token%}
        <label>아이디</label>
        <input id="email" class="form-control" id="{{ form.email.id_for_label }}" maxlength="50" name="{{ form.email.html_name }}" type="text" />
        <label>패스워드</label>
        <input id="password" class="form-control" id="{{ form.password.id_for_label }}" maxlength="120" name="{{ form.password.html_name }}" type="password" />
        <input type="submit" id="submit" class="save btn btn-success" value="로그인">              
        </form>
      
      </div>
    </div>
  </div>
  
</div>
      

<script src="{% static 'hipdrobe/js/login.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

</body>
</html>







  
  

src/web/hipdrobe/templates/hipdrobe/login_Fail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>
document.addEventListener("DOMContentLoaded", function(event) {
  Swal.fire({
  width: 350,
  icon: 'error',
  title: 'Oops...',
  text: '입력 정보를 다시 확인해 주세요:(',
  confirmButtonText:'확인',
}).then(()=>{window.history.back()})
      });

</script>
<body>

</body>
</html>

src/web/hipdrobe/templates/hipdrobe/min.html
{% extends 'base.html' %}
{% load static %}
{% block title %}타이틀{% endblock %}
{% block local_head_resources %}
  <link rel="stylesheet" href="{% static 'hipdrobe/css/xxx.css' %}">
{% endblock %}
{% block bg %}
{% endblock %}
{% block content %}
  <div class="container-fluid content-wrap">
    <div class="content-main">
      <h1>content-main</h1>
      
    </div>
    <div class="content-info">
      <h3>content-info</h3>

    </div>
  </div>
{% endblock %}
{% block local_body_resources %}
  <script src="{% static 'hipdrobe/js/xxx.js' %}"></script>
{% endblock %}

src/web/hipdrobe/templates/hipdrobe/signup.html
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    {% load static %}
		<title>Hipdrobe 회원가입</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- MATERIAL DESIGN ICONIC FONT -->
		<link rel="stylesheet" href="{% static 'hipdrobe/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css'%}">
		<link rel="shortcut icon" href="{% static 'hipdrobe/favicon/favicon.ico' %}" type="image/x-icon">
		<link rel="icon" href="{% static 'hipdrobe/favicon/favicon.ico' %}" type="image/x-icon">

		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'hipdrobe/css/signup.css'%}">
	</head>

{% if user.is_authenticated %}
<script type="text/javascript">
  alert('잘못된 접근입니다. \n회원가입을 위해서는 로그아웃이 필요합니다.')
  window.location.href = '/';
</script>
{% else %}
	<body>

		<div class="wrapper">
			<div class="inner">
				<div class="image-holder">
					
          <video id="video" preload="auto" autoplay="true" loop="loop" muted="muted" volume="0" style="
          width: 800px;
          height: 510px;
      ">
            <source src="{%static 'hipdrobe/img/regist_images/mov.mp4'%}">
          </video>
				</div>
				<form method='post' action="{% url 'hipdrobe:signup'%}">
            {%csrf_token%}
          <h3>Sign up</h3>
		  {% for field in form %}
		  {{ field.label }}
		  {{field}}
          
					<!-- <div class="form-group">
						<input type="text" placeholder="First Name" class="form-control">
						<input type="text" placeholder="Last Name" class="form-control">
					</div> -->
					<!-- <div class="form-wrapper">
						<input type="text" id="{#{ form.username.id_for_label }}"placeholder="Username" class="form-control">
						<i class="zmdi zmdi-account"></i>
					</div> -->
					<!-- <div class="form-wrapper">
						<input type="email" id="{#{ form.email.id_for_label }}" placeholder="Email Address" class="form-control">
						<i class="zmdi zmdi-email"></i>
					</div> -->
					<!-- <div class="form-wrapper">
						<select name="" id="{{ form.gender.id_for_label }}" class="form-control">
							<option value="" disabled selected>Gender</option>
							<option value="True">Male</option>
							<option value="False">Female</option>
							
						</select>
						<i class="zmdi zmdi-caret-down" style="font-size: 17px"></i>
					</div> -->
					<!-- <div class="form-wrapper">
						<input type="password" id="{#{ form.password.id_for_label }}" placeholder="Password" class="form-control">
						<i class="zmdi zmdi-lock"></i>
					</div> -->
					{% endfor %}

					<!-- <div class="form-wrapper">
						<input type="password" placeholder="Confirm Password" class="form-control">
						<i class="zmdi zmdi-lock"></i>
					  </div> -->  
          			<div>
					<button type="submit">Register
						<i class="zmdi zmdi-arrow-right"></i>
          			</button>
          			</div>
            <br>
            <br>
          <div style="float:right;">
          
              <a href="{% url 'hipdrobe:index'%}" >Main</a>
          
          </div>
          <div style=" float: left;">
          
              <a href="{% url 'hipdrobe:signin'%}" >Login</a>
          
          </div>

        </div>
        </form>
        {%endif%}
			</div>
		</div>
		
	</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

src/web/hipdrobe/templates/hipdrobe/wardrobe-coordi-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}힙드로브-코디 보기{% endblock %}
{% block local_head_resources %}
  <link rel="stylesheet" href="{% static 'hipdrobe/css/narrow.css' %}">
  <link rel="stylesheet" href="{% static 'hipdrobe/css/bg-white.css' %}">
  <link rel="stylesheet" href="{% static 'hipdrobe/css/char-win.css' %}">
  <link rel="stylesheet" href="{% static 'hipdrobe/css/wardrobe-coordi-detail.css' %}">
{% endblock %}
{% block bg %}
{% endblock %}
{% block content %}
  {% include 'hipdrobe/include/_wardrobe-link.html' %}
  <div class="container-fluid content-wrap ctnt-center">
    <!-- main content section -->
    <div class="content-main">
      <br>
      <div class="row mb-3">
        <div class="col-8">
          <h3 class="heading">My Coordi Detail</h3>
        </div>
      </div>

      <div class="row">
        <div class="card-group">
          <div class="card">
          </div>
        </div>
      </div>

      <div class="row btn-wrapper">
        <div class="btn-group">

          <a href="javascript:history.back()" class="btn btn-primary">돌아가기</a>
          <a href="{% url 'hipdrobe:coordi_update' data.id %}" class="btn btn-warning">수정하기</a>
          <button class="btn btn-danger" onclick="confirmDelete(event)">삭제하기</button>
    
        </div>
      </div>
    </div>


    

    <!-- info section -->
    <div class="content-info">
      <div>
        <p>T</p>
        <p>B</p>
        <p>D</p>
      </div>
    </div>
  </div>
  <input type="hidden" value="{{data}}" id="hidden-data"/>
  <div class="modal fade" id="id-modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">정말 삭제할까요?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        삭제한 코디는 다시 되돌릴 수 없습니다.<br>
        정말 삭제할까요?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
        <button type="button" class="btn btn-danger" onclick="deleteCoordi(event)">삭제하기</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content-bottom %}
  {% include 'hipdrobe/include/_wardrobe-additem.html' %}
  {% include 'hipdrobe/include/_items_modal.html' %}
{% endblock %}
{% block local_body_resources %}
  <script src="{% static 'hipdrobe/third-party-etc/displace.js' %}"></script>
  <script src="{% static 'hipdrobe/js/char-win.js' %}"></script>
  <script src="{% static 'hipdrobe/js/apis-cruditem.js' %}"></script>
  <script src="{% static 'hipdrobe/js/wardrobe-coordi-detail.js' %}"></script>
{% endblock %}