src/web/config/urls.py
from django.contrib import admin
from django.urls import path, include


# for clothes static path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("hipdrobe.urls")),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),


]


urlpatterns += static(settings.CLOTHES_URL, document_root=settings.CLOTHES_ROOT)
urlpatterns += static(settings.CLOTHES_URL_TMP, document_root=settings.CLOTHES_ROOT_TMP)

src/web/hipdrobe/urls.py
from django.urls import path
from . import views, apis
# from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views


app_name = "hipdrobe"
urlpatterns = [
    path('', views.index, name='index'),
    path('wardrobe/items/', views.items, name="items" ),
    path('wardrobe/coordi/', views.coordi, name="coordi"),
    path('wardrobe/coordi/<int:c_id>/detail/', views.coordi_detail, name="coordi_detail"),
    path('wardrobe/coordi/<int:c_id>/update/', views.coordi_update, name="coordi_update"),
    path('wardrobe/stat/', views.stat, name="stat" ),
    
    path('signup/',views.signup, name="signup"),
    path('login/' ,views.signin, name="signin"),
    path('logout/' ,views.logout, name="logout"),

    # auth_views 이용
    # path('signup/', views.UserCreateView.as_view(), name='signup'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    




    # 페이지 요청이 아닌 기능 요청은 아래쪽에서 관리
    # 대표적으로 AJAX 요청이 여기에 해당
    path('apis/parts/', apis.parts, name="parts"),
    path('apis/cate1/', apis.cate1, name="cate1"),
    path('apis/cate2/', apis.cate2, name="cate2"),
    path('apis/upload/', apis.upload, name="upload"),
    path('apis/clothes/', apis.clothes, name="clothes"),
    path('apis/additem/', apis.additem, name="additem"),
    path('apis/coordi/', apis.coordi, name="coordi_list"),
    path('apis/coordi/new/', apis.coordi_new, name="coordi_new"),
    path('apis/coordi/delete/', apis.coordi_delete, name="coordi_delete"),
    path('apis/coordi/edit/', apis.coordi_edit, name="coordi_edit"),
    path('apis/daily-status/', apis.daily_status, name="daily_status"),
    # path('check_id/',views.check_id,name="check_id"),
    path('apis/clothes_detail/', apis.clothes_detail, name="clothes_detail"),
    path('apis/updateitem/', apis.updateitem, name="updateitem"),
    path('apis/delete_clothes/', apis.delete_clothes, name="delete_clothes"),
]

src/web/config/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <!-- global resources -->
    <link rel="shortcut icon" href="{% static 'hipdrobe/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'hipdrobe/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'hipdrobe/css/global.css' %}" />
    
    
    



    <!-- local resources -->
    {% block local_head_resources %}
    {% endblock %}
</head>

<body>
    <div id="loading">
        <img src="{% static 'hipdrobe/img/square-grid-loader.svg' %}"/>
    </div>
    
    <!-- Wrapper -->
    <div class="wrapper">
        {% block bg %}
        {% endblock %}

        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="{% url 'hipdrobe:index' %}">
                    <div id="brand-main">HIP</div>
                    
                    <h1 class="ml7">
                        <span class="text-wrapper">
                          <span class="letters">Wardrobe</span>
                        </span>
                      </h1>
                    
                    <div id="brand-main-hangeul">
                        <img src="{% static '/hipdrobe/img/brand-g-wh.svg'%}" alt="힙드로브"/>
                    </div> 
                    
                </a>
            </div>
            <ul class="list-unstyled components">
                <li id="main-ln-wardrobe" class="">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">나만의 옷장</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'hipdrobe:items' %}">내 옷장 보기</a>
                        </li>
                        <li>
                            <a href="{% url 'hipdrobe:coordi' %}"> 코디 작성</a>
                        </li>
                        <li>
                            <a href="{% url 'hipdrobe:stat' %}">힙-스탯</a>
                        </li>
                        <li>
                            <a href="#">방명록</a>
                        </li>
                        <li>
                            <a href="#">거래</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">랭킹 보기</a>
                </li>
                <li>
                    <a href="#">입는다그램</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content-->
        <div id="content">
            <nav id="id-nav-narrow" class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'hipdrobe/img/brand.png' %}" width="45" height="45" class="d-inline-block align-top" alt="">
                    HIPdrobe
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        {% if user.is_active %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">{{user.username}}님 환영합니다</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'hipdrobe:logout' %}">로그아웃</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'hipdrobe:signin' %}">로그인</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'hipdrobe:signup' %}">회원가입</a>
                            </li>
                        {% endif %}
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            나만의 옷장
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'hipdrobe:items' %}">내 옷장 보기</a>
                            <a class="dropdown-item" href="{% url 'hipdrobe:coordi' %}">코디 작성</a>
                            <a class="dropdown-item" href="{% url 'hipdrobe:stat' %}">힙-스탯</a>
                            <a class="dropdown-item" href="#">방명록</a>
                            <a class="dropdown-item" href="#">거래</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">랭킹 보기</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">입는다그램</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <nav id="id-div-nav-sub" class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <div>
                        <p id="page-title"></p>&nbsp;&nbsp;<p id="page-title-sub"></p>
                    </div>
                    <div id="log-section">
                        <ul>
                        <li class="login-info" style="font-size:2em;">
                            <!-- <a data-toggle="modal" href="#exampleModal">로그인</a> -->
                            {% if user.is_active %}
                            <li><a href="{%url 'hipdrobe:signin' %}"> <span class="glyphicon glyphicon-heart"></span></a></li>
                            <span>{{user.username}}님 환영합니다</span>
                            <li><a href="{% url 'hipdrobe:logout' %}">로그아웃</a></li>
                                
                            {% else %}
                            <li><a href="{% url 'hipdrobe:signin' %}"> <span class="glyphicon glyphicon-user"></span> 로그인</a></li>
                            <li><a class="nav-link" href="{% url 'hipdrobe:signup' %}">회원가입</a></li>
                            {% endif %}
                        </li>
                            
                                
                            </li>

                            <li class="meta-info2" style="font-size:2em;">
                                도움말
                            </li>
                            <li class="meta-info2">
                                <div class="icon">
                                    <i class="fas fa-comment-alt" style="font-size:1.3em;"></i>
                                </div>
                                <div class="num">
                                    <span id="alert-cnt">0</span>
                                </div>
                            </li>
                        </ul>
                    </div>                    
                </div>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% block content-bottom %}
    {% endblock %}

    <!-- Footer -->
    <footer id="footer">
        <hr>
        <div class="footer-wrap">
            <div>
                <p>
                    멀티캠퍼스 아이디어톤 프로젝트 <span class="foot-brand">Hipdrove</span>(힙드로브)<br>
                    [4차 5기] Open-API(B) Team <span class="foot-team">Passion Leader</span>(패션리더) <span class="italic">all right reserved</span>
                </p>
            </div>
            <div>
                <h3 class="italic"><a href="#"><ins>Contact us</ins></a></h3>
            </div>
        </div>
    </footer>

    {% include 'hipdrobe/include/_success_modal.html' %}

    <!-- global body resources -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <!-- text effect -->
    <script src="{% static 'hipdrobe/js/global.js' %}"></script>
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

    <!-- local body resources -->
    {% block local_body_resources %}
    {% endblock %}
</body>

</html>

src/web/config/templates/bd-carousel.html
<!-- carousel -->
{% load static %}
<div class="bg bd-carousel">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
          <img src="{% static 'hipdrobe/img/bg_index01.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </div>
      </div>
      <div class="carousel-item">
          <img src="{% static 'hipdrobe/img/bg_index02.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
      </div>
      <div class="carousel-item">
          <img src="{% static 'hipdrobe/img/bg_index03.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
          </div>
      </div>
    </div>
    <!--
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    -->
  </div>
</div>

src/web/config/templates/char-win-control.html
<!-- character window control -->

src/web/config/templates/char-win.html
<!-- character window -->
<!-- test code -->
<!--
<div id="id-div-char-win" ondrop="itemDrop(event)" ondragover="itemDragOver(event)">
  <div id="id-div-char-head" class="char-slot" draggable="true" ondragstart="itemDragStart(event)"></div>
</div>
-->

<div id="id-div-char-win">
    <div class="moveable" ></div>
    <div class="moveable" ></div>
    <div class="moveable" ></div>
</div>

src/web/config/templates/wardrobe-link.html
<!-- wardrobe link & weather -->
<div class="container-fluid content-head ctnt-center">
    <ul>
      <li id="ln-items">
        <a href="{% url 'hipdrobe:items' %}">내 옷장 보기</a>
      </li>
      <li>|</li>
      <li id="ln-coordi">
        <a href="{% url 'hipdrobe:coordi' %}">코디 작성</a>
      </li>
      <li>|</li>
      <li id="ln-stat">
        <a href="{% url 'hipdrobe:stat' %}">힙-스탯</a>
      </li>
      <li>|</li>
      <li>
        <a href="#">방명록</a>
      </li>
      <li>|</li>
      <li>
        <a href="#">거래</a>
      </li>
    </ul>
    <hr>
</div>